# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Benjamin Leister"
email: benji.leister@gmx.de
description: >- # this means to ignore newlines until "baseurl:"
  Hello, my name is Benjamin Leister, I am 20 years old and currently working freelance as a translator for English, German and Spanish. I use this page for work-references.
  If you are interested, inform me by using either my E-Mail or my LinkedIn Account below.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ventustranslations.github.io" # the base hostname & protocol for your site, e.g. http://example.com

header_image: assets/profile.png

#comments: true
disqus: purelog-jekyll

author: Benjamin Leister
author_bio: >-
  TODO:BIO
author_pic: https://brennanbrown.ca/img/avatar.png
paginate: 4
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Benjamin Leister
      avatar: assets/profile-sm.png

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
